---
# Nombre del workflow (aparecer치 en la GUI)
name: hello-world
# Cu치ndo se ejecuta: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: [push, pull_request]
# Listado de jobs
jobs:
  # ID del job. Cada job se ejecuta en una m치quina nueva
  unit-test:
    # Tipo de m치quina. Puede ser de Github o un self-hosted runner:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Run unit tests
      run: go test ./...
    - name: Build docker Image
      uses: docker build -t v0.1 .
